name = "ATAC"
logo = """            █
   ██       █       ██
  ████ █  ████   █ ████
    ███     █     ███
      █████████████
   ████████████████ ██
   ██ ███████   ███ ██
  ███ ███████   ███ ███
  ███  ██████  ███  ███
   ███ ██████ ████ ███
    ██ ███████████ ██
       █  █████  █
            █"""
binary_path = "atac"
args = ["--dry-run"]
padding = [0, -1]