name = "ATAC"

command = "/home/julien/.cargo/bin/atac"
args = ["--dry-run"]

[taskbar]
position = 0
commands = []

[window]
resizable = true
close_button = true
fixed_position = false

[terminal]
padding = [0, -1]
background_color = { r = 30, g = 30, b = 30 }