name = "Bluetooth"
logo = """       ██████████
     ██████ ███████
    ███████  ███████
    ███████    █████
    ████  █  █  ████
    ████        ████
    ██████    ██████
    █████      █████
    ████  █  █  ████
    ███████    █████
    ███████   ██████
     ██████ ███████
       ██████████"""
binary_path = "bluetui"
args = []
padding = [0, 0]