name = "Resources"

command = "btop"
args = []

[taskbar]
position = 2

[window]
resizable = true
close_button = true
fixed_position = false
size = { width = 82, height = 26 }

[terminal]
padding = [0, 0]